version: '3'
services:
  insight:
    image: insight
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8022:22"
    volumes:
      - ./workspace:/workspace
      - /home:/home
    ipc: host
    restart: always     # or "unless-stopped"
    environment:
      PYTHONIOENCODING: utf-8
      # pass: developer | https | home folder contains "mycert.pem" and "mykey.key" files
      command: jupyter lab --ip=0.0.0.0 --port=8080 --no-browser --allow-root --NotebookApp.password=sha1:d19b8bedeba6:2ad4439abacb4f77ca5f3b790059451863745849 --NotebookApp.terminado_settings='{"shell_command":["/bin/bash"]}'z
volumes:
  insight:
